"""`fleet apps` — browse the pve-community-nix catalog from the consumer CLI.

Loaded by fleetkit's CLI extension hook ([cli].extensions_dir in
fleet.toml). Reads the catalog JSON artifact the consumer flake re-exports
as `.#catalog-json` (built, never `nix eval`'d at runtime — fleetkit's
rule for Nix→CLI data) and caches it under .cache/fleet/.
"""
from __future__ import annotations

import json
import subprocess
from pathlib import Path

import click

CACHE = Path(".cache/fleet/catalog.json")


def _load(refresh: bool = False) -> dict:
    if refresh or not CACHE.exists():
        out = subprocess.run(
            ["nix", "build", "--no-link", "--print-out-paths", ".#catalog-json"],
            check=True, capture_output=True, text=True).stdout.strip()
        CACHE.parent.mkdir(parents=True, exist_ok=True)
        CACHE.write_text(Path(out).read_text())
    return json.loads(CACHE.read_text())


@click.group("apps")
def apps() -> None:
    """Browse the application catalog and scaffold app hosts."""


@apps.command("list")
@click.option("--category", "-c", help="Only this category.")
@click.option("--impl", help="Only this impl tier (planned, nixos-service, package-systemd, oci, image, unsupported).")
@click.option("--status", help="Only this status (planned, ported, verified).")
@click.option("--refresh", is_flag=True, help="Rebuild the catalog JSON first.")
def list_(category, impl, status, refresh) -> None:
    """List catalog entries."""
    cat = _load(refresh)
    rows = []
    for slug, e in sorted(cat.items()):
        if category and e.get("category") != category:
            continue
        if impl and e.get("impl") != impl:
            continue
        if status and e.get("status") != status:
            continue
        rows.append((slug, e.get("category", ""), str(e.get("port") or "-"), e.get("impl", ""), e.get("status", "")))
    if not rows:
        click.echo("no entries match")
        return
    w = [max(len(r[i]) for r in rows) for i in range(5)]
    click.echo("  ".join(h.ljust(w[i]) for i, h in enumerate(["app", "category", "port", "impl", "status"])))
    for r in rows:
        click.echo("  ".join(c.ljust(w[i]) for i, c in enumerate(r)))
    click.echo(f"{len(rows)} entries")


@apps.command("show")
@click.argument("app")
def show(app) -> None:
    """Show one catalog entry as JSON."""
    cat = _load()
    if app not in cat:
        raise click.ClickException(f"no catalog entry {app!r}")
    click.echo(json.dumps(cat[app], indent=2, sort_keys=True))


@apps.command("scaffold")
@click.argument("app")
@click.option("--vmid", type=int, required=True)
@click.option("--node", required=True, help="PVE node name.")
@click.option("--ip", required=True, help="Internal IPv4 (bare).")
@click.option("--provider", default="proxmox.main", show_default=True)
@click.option("--env", "env_", default="home", show_default=True)
@click.option("--stack", default=None, help="Defaults to the app's category.")
@click.option("--out", type=click.Path(), default=None, help="Write to this file (default: fleet/hosts/<app>.nix).")
def scaffold(app, vmid, node, ip, provider, env_, stack, out) -> None:
    """Write a fleet/hosts/<app>.nix mkApp file from the preset."""
    cat = _load()
    if app not in cat:
        raise click.ClickException(f"no catalog entry {app!r}")
    e = cat[app]
    if e.get("impl") == "unsupported":
        raise click.ClickException(f"{app} is unsupported: {e.get('unsupportedReason', '')}")
    stack = stack or e.get("category", "apps")
    gpu = '  gpu = "intel";                  # intel | amd | nvidia\n' if (e.get("devices") or {}).get("gpu") else ""
    text = f'''# {e.get("title", app)} — generated by `fleet apps scaffold {app}`; edit freely.
catalog:
catalog.lib.mkApp {{
  app = "{app}";
  compute = {{
    env = "{env_}"; stack = "{stack}";
    provider_instance = "{provider}";
    vm_id = {vmid};
    node = "{node}";
    internal_ip = "{ip}";
  }};
{gpu}  nixos = {{ }};
}}
'''
    path = Path(out) if out else Path("fleet/hosts") / f"{app}.nix"
    if path.exists():
        raise click.ClickException(f"{path} exists — remove it or pass --out")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)
    click.echo(f"wrote {path}; add `(import ./hosts/{app}.nix catalog)` to fleet/default.nix imports")


COMMANDS = [apps]
